### PR TITLE
WIP: Support for Securitas Direct API

### PR DESCRIPTION
**Pull request by ptz0n**
For some time it's been a requested feature of [homebridge-verisure](https://github.com/ptz0n/homebridge-verisure) to support Securitas Direct installations. I argue that this actually make sense from a user perspective, as these are often nowadays branded as Verisure.

I don't personally have access to such a system, but thanks to @Cebeerre who put a lot of effort into [documenting the API](https://github.com/Cebeerre/VerisureEUAPI) this is now within reach of development.

This should allow integrations with Securitas Direct systems with mobile access in the following countries:

- Spain
- Italy
- France
- United Kingdom
- Portugal

### 1. Install the module from this branch.
```bash
npm install git://github.com/ptz0n/node-verisure.git#securitas-direct
```

### 2. Put the following lines into a file called `test.js`
Then replace `username`, `password` and `country` on line 3 with values for your system. Country should be set to one of `es`, `fr` or `pt`:
```js
const SecuritasDirect = require('verisure/es');

const client = new SecuritasDirect('username', 'password', 'country');

const run = async () => {
  await client.login().catch((error) => {
    console.error('Oh, no!', error.response.status, error.response.data);
  });

  console.log('Success!');

  await client.logout();
}

run();

```

### 3. Run it with the following command
```bash
node test.js
```

### 4. Additional info of your environment

```bash
node -v && npm -v
```

### 5. Paste the output as comments here below 👇
The test script should not output any secrets about your system but please read through the output before posting. I will try to promptly remove any such information if posted.

---

- Feature request: https://github.com/ptz0n/homebridge-verisure/issues/80
- Feature request: https://github.com/ptz0n/homebridge-verisure/issues/39
- Reference client: https://github.com/Cebeerre/VerisureAPIClient

### CODE REVIEW

**Comment by gabriuelucho** [comment]
Hi
I would like to help as much as I can, but unfortunately I'm a noob on these things. I've made the installation but I have no idea about how can I test it...
Please could you give me some steps to follow? 
Thank you!

**Comment by ptz0n** [comment]
@gabriuelucho Great feedback! I've updated the description above with step by step instructions. Please reach out again if you get stuck at any point. Looking forward to the results.

**Comment by gabriuelucho** [comment]
> @gabriuelucho Great feedback! I've updated the description above with step by step instructions. Please reach out again if you get stuck at any point. Looking forward to the results.

Thank you for your help, here you are the results, seems there was no luck

`pi@raspberrypi:~ $ node test.js
Oh, no! 200 { PET:
   { RES: [ 'ERROR' ],
     ERR: [ '3000' ],
     MSG: [ 'Por favor, vuelva a escribir sus datos de acceso' ] } }
pi@raspberrypi:~ $ node -v && npm -v
v10.16.3
6.9.0
`
Hope it helps, let me know if I can do any other test

**Comment by artik** [comment]
Same here:

`/homebridge/node_modules/verisure # node test.js                                                                            
Oh, no! 200 {                                                                                                               
  PET: {                                                                                                                    
    RES: [ 'ERROR' ],                                                                                                       
    ERR: [ '3000' ],                                                                                                        
    MSG: [ 'Por favor, vuelva a escribir sus datos de acceso' ]                                                             
  }                                                                                                                         
}                                                                                                                           
`

**Comment by ptz0n** [comment]
@gabriuelucho @artik Thanks a lot for the speedy tests! Sorry that it did not work as intended.

I’ll have another look to see what might be wrong.

**Comment by artik** [comment]
@ptz0n Do you want me to change with a temporary pwd, and give you my access ?

**Comment by ptz0n** [comment]
@artik That would be helpful! Is it possible to create a read-only user for testing purposes?  Please email erik@eng.se

**Comment by artik** [comment]
Email set ;)

**Comment by ptz0n** [comment]
__Client updated__ - Please follow all the steps from the top to try again.

**Comment by artik** [comment]
Haha! great job!

```
/homebridge/node_modules/verisure # node test.js                                                                            
Success! 
```

**Comment by gabriuelucho** [comment]
yeah!

pi@raspberrypi:~ $ node test.js
Success!

**Comment by ptz0n** [comment]
I decided to move this logic to it's own module.

First version published: https://github.com/ptz0n/node-securitas-direct

**Pull request closed without merging**
